---
version: "3.2"

volumes:
   yum-volume:

services:
  registry_init:
    build: "docker/registry_init"
    network_mode: "host"
    restart: "no"
    env_file: "./config.env"
    depends_on:
      - registry
  registry:
    image: "registry:2"
    network_mode: "host"
    restart: "always"
    volumes:
      - /var/tmp/auth:/auth
      - /etc/pki/tls/certs:/certs
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/apache.crt
      REGISTRY_HTTP_TLS_KEY: /certs/apache.key
    ports:
      - "5000:5000"
  apache:
    build: "docker/apache"
    restart: "always"
    network_mode: "host"
    volumes:
      - type: volume
        source: yum-volume
        target: /var/www/html
      - type: bind
        source: /etc/pki/tls/certs/pypi.python.org.crt
        target: /usr/local/apache2/conf/pypi.python.org.crt
      - type: bind
        source: /etc/pki/tls/certs/pypi.python.org.key
        target: /usr/local/apache2/conf/pypi.python.org.key
      - type: bind
        source: /etc/pki/tls/certs/download.docker.com.crt
        target: /usr/local/apache2/conf/download.docker.com.crt
      - type: bind
        source: /etc/pki/tls/certs/download.docker.com.key
        target: /usr/local/apache2/conf/download.docker.com.key
      - type: bind
        source: /etc/pki/tls/certs/dl.fedoraproject.org.crt
        target: /usr/local/apache2/conf/dl.fedoraproject.org.crt
      - type: bind
        source: /etc/pki/tls/certs/dl.fedoraproject.org.key
        target: /usr/local/apache2/conf/dl.fedoraproject.org.key
      - type: bind
        source: /etc/pki/tls/certs/apache.crt
        target: /usr/local/apache2/conf/server.crt
      - type: bind
        source: /etc/pki/tls/certs/apache.key
        target: /usr/local/apache2/conf/server.key
      - type: bind
        source: ${PWD}/docker/apache/conf/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: ${PWD}/docker/apache/conf/extra/httpd-ssl.conf
        target: /usr/local/apache2/conf/extra/httpd-ssl.conf
